name: anime_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  get: ^4.6.6
  http: ^1.2.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_screenutil: ^5.9.3
  ionicons: ^0.2.2
  awesome_extensions: ^2.0.18
  bottom_navy_bar: ^6.1.0
  loading_animations: ^2.2.0
  salomon_bottom_bar: ^3.3.2
  lottie: ^3.1.3
  flutter_animate: ^4.5.0
  sliver_snap: ^1.2.0
  buttons_tabbar: ^1.3.13
  intl: ^0.19.0
  skeletonizer: ^1.4.2
  youtube_player_flutter: ^9.1.1
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  google_sign_in: ^6.2.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
